name: release

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pvcnt/reviewer
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package chart
        run: helm package production/helm/reviewer --version 0.0.${{ github.run_number }} --destination dist
      - name: Push chart
        run: helm push dist/*.tgz oci://ghcr.io/pvcnt/helm
